#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/pan3dme/flutterfile/sdk/flutter_3.30.0"
export "FLUTTER_APPLICATION_PATH=/Users/pan3dme/Desktop/oframe/flutter/flutter/100-DaysOf-Futter-main/fitness_app"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/pan3dme/Desktop/oframe/flutter/flutter/100-DaysOf-Futter-main/fitness_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "CONFIGURATION_BUILD_DIR=/Users/pan3dme/Desktop/oframe/flutter/flutter/100-DaysOf-Futter-main/fitness_app/build/ios/iphoneos"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/pan3dme/Desktop/oframe/flutter/flutter/100-DaysOf-Futter-main/fitness_app/.dart_tool/package_config.json"
